# DataFrame ->
Combination of multiple data series called data frames

In [1]:
import numpy as np
import pandas as pd

# Creating DataFrame

In [3]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:

data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
] # column header name nhi ayenge to manually set krna pdega
df2 = pd.DataFrame(data_list)
columns = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns = columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

# Selection and Indexing of Columns

In [13]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
# df2[0] # this will not here columns name will work

In [16]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [18]:
df2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [19]:
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

# Creating a new column

In [22]:
df2["Designation"] = ['Doctor','Eng.','Doctor','Eng.']

In [23]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

# Removing Columns

In [25]:
df2.drop('Designation',axis = 1) # main data se remove nhi hota hai

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [26]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

In [33]:
# df2.drop('Designation',axis = 1,inplace=True) # for removing from main data

In [32]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [34]:
# multings thingd to remove 
df2.drop(['City','Salary'],axis = 1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [35]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [36]:
df2.drop(0,axis=0) # axis = 0 -> horizontal

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

# Selsecting Rows

In [37]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [38]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [40]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [41]:
#or iloc-> index location
df.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

# Selecting Subsets of Rows and Columns

In [43]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [44]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

# Conditional Selections

In [45]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [48]:
# I only want to see those people whose age is above 30

In [49]:
df2[df2['Age'] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [50]:
# I only want people whose age is above 30 and their city must be paris

In [52]:
df2[(df2['Age'] >30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000