In [1]:
import numpy as np 
import pandas as pd

# Finding Missing Data

In [15]:
data = {
    'A' : [1,2,np.nan,4,5],
    'B' : [1,2,3,4,5],
    'C' : [1,2,3,np.nan,np.nan], 
    'D' : [1,np.nan,np.nan,np.nan,5]
}
df = pd.DataFrame(data)

In [16]:
# nan = not a number

In [17]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [18]:
# find no of nan
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [19]:
# any mising value in each columna
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# Removing Missing Data

works on row basis

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df.dropna()# all rows deleted which have null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [24]:
# threshold 
df.dropna(thresh=3) # jiske pas atleast 3 non null values hai unhe chorke sabko dlt kr do

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

# Filling the Missinf Data

In [25]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [27]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [28]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
values = {"A" : 0,"B" :100,"C":300,"D":400}
df.fillna(value = values) # columns wise

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [31]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [32]:
# means se fill kro  -> column wise
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0